name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  core:
    name: Build core project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate BuildConfig
        run: ./gradlew generateBuildConfig
      - name: Build with Gradle
        run: ./gradlew jar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Jar
          path: build/libs

